
# LAYER DETECTION ALGOTHIM
deltaNorm = 3

# THE HIGHER THE avg_Points_Cloud_Mask, THE WORSE THE MASK WILL BE
avg_Points_Cloud_Mask = 1
std_factor_layer_mask = 1.0 
stepScanCloud = 1

DELTA_RANGE_LIM_BINS = 10
CLOUD_MIN_THICK = 1

# CLOUD DETECTION PARAMETERS
COMPUTE_PBL_MASK = YES
COMPUTE_LAYER_MASK = YES

winGluing = 1000

wl_factor = 1.0
