
L0="yes"
L1="yes"
L2="yes"

PATH_TO_LPP = /home/juan/LPP/
PATH_IN = /mnt/c/lidarData/SPU/2020/
FILE_CONF = /home/juan/LPP/Lidar_Configuration_Files/analysisParameters_SPU.conf
Path_To_Molecular_File = /mnt/c/lidarData/SPU/Radiosonde/
PATH_TO_OUTPUT = /mnt/c/lidarData/SPU/Results/
