#!/bin/bash

# INPUT FOLDER FOR mergeLidarFiles
# PATH_IN_RAW="./signalsTest/Brazil_14/"
PATH_IN_RAW="./signalsTest/20180619/"
# PATH_OUT_RAW="./signalsTest/Brazil_14/OUT/"
PATH_OUT_RAW="./signalsTest/20180619/OUT/"
FILE_OUT_MERGED="merged_SCC_20180619.nc"
# FILE_OUT_MERGED="merged_LALINET_20180619.nc"
PATH_FILE_OUT_MERGED=$PATH_OUT_RAW$FILE_OUT_MERGED

# INPUT PATHS AND FILE FOR lpp1
PATH_IN_PDL1=$PATH_OUT_RAW
FILE_IN_PDL1=$FILE_OUT_MERGED
PATH_FILE_IN_PDL1=$PATH_IN_PDL1$FILE_IN_PDL1
# OUTPUT PATHS AND FILE FOR lpp1
PATH_OUT_PDL1=$PATH_OUT_RAW
# FILE_OUT_PDL1="merged_20180619_PDL1.nc"
FILE_OUT_PDL1="merged_20110714_PDL1.nc"
PATH_FILE_OUT_PDL1=$PATH_OUT_PDL1$FILE_OUT_PDL1

# INPUT PATHS AND FILE FOR lpp2
PATH_IN_PDL2=$PATH_OUT_RAW
FILE_IN_PDL2=$FILE_OUT_MERGED
PATH_FILE_IN_PDL2=$PATH_IN_PDL2$FILE_IN_PDL2
# OUTPUT PATHS AND FILE FOR lpp2
PATH_OUT_PDL2=$PATH_OUT_RAW
FILE_OUT_PDL2="merged_LALINET_2018619_PDL2.nc"
PATH_FILE_OUT_PDL2=$PATH_OUT_PDL2$FILE_OUT_PDL2

